### ISSUE TITLE
Not able to install :  conda install bioconductor-deseq2

### ISSUE THREAD

**Issue by midhunks** [ljdursi/glbio-jupyter-workshop#1]
It says not available for windows

[python3] C:\Users\Username>conda install bioconductor-deseq2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .
**Error:  Package missing in current win-64 channels:**
- bioconductor-deseq2

You can search for this package on anaconda.org with

```
anaconda search -t conda bioconductor-deseq2
```

**Comment by ljdursi** [comment]
Ah, thanks.  Hmm.

I don't have access to a windows machine - could you please try the following for me:
- run the R _installed as part of anaconda_, eg anaconda3/bin/R
- From there, run the bioconductor process the usual way:

```
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite(c('DESeq2'))
```
- and then see if it works by starting the Jupyter notebook, under "New" start an R notebook, and in a cell enter 

```
library(DESeq2)
help(DESeq)
```

and click Cell>Run and see if that works?

If it does, I'll update the instructions accordingly; otherwise I'll have to change the example that uses DESeq2...

**Comment by sunworshipper** [comment]
This worked for me.  I had exactly the same error in 2019 so hopefully this helps someone.
In an activated r environment terminal:

conda install r-RCurl
conda install r-XML
conda install r-RcppArmadillo

then open a notebook and in a cell execute:

source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite(c('DESeq2'))
